### ISSUE TITLE
What license applies?

### ISSUE THREAD

**Issue by rekado** [TaylanUB/scheme-srfis#2]
It is not obvious to me what license or licenses apply to the source files.  Could you please clarify what the effective license is?

Thank you!

**Comment by TaylanUB** [comment]
Hi rekado,

Every non-trivial source file contains its own license notice, because
about 90% of the project consists of wrapping reference implementations
in library boilerplate, and they all have their own licensing notice.

Almost all SRFIs seem to use this license or a similar one:

;; Permission is hereby granted, free of charge, to any person obtaining
;; a copy of this software and associated documentation files (the
;; "Software"), to deal in the Software without restriction, including
;; without limitation the rights to use, copy, modify, merge, publish,
;; distribute, sublicense, and/or sell copies of the Software, and to
;; permit persons to whom the Software is furnished to do so, subject to
;; the following conditions:

;; The above copyright notice and this permission notice shall be
;; included in all copies or substantial portions of the Software.

So kind of a generic non-copyleft free software license I guess.

I suppose I could still add a LICENSE file that specifies that any
code that isn't under its own license notice is licensed under XYZ.

-- 
Taylan

**Comment by TaylanUB** [comment]
Added a LICENSE file.
